Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -52,73 +52,73 @@ jobs:
           scp -i private_key.pem -r ./* $SSH_USERNAME_1@$SSH_HOST_1:/home/$SSH_USERNAME_1/backend-$DEPLOY_ENV/
 
 
-          ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF
-            cd /home/$SSH_USERNAME_1/backend-$DEPLOY_ENV
-            sudo apt update
-            sudo apt install npm -y
-            sudo npm install -g pm2 -y
-            if [ -f package.json ]; then
-              npm install
-            else
-              echo "package.json not found!"
-              exit 1
-            fi
-            if [ -f index.js ]; then
-              pm2 stop backend-$DEPLOY_ENV || true
-              pm2 start index.js --name backend-$DEPLOY_ENV --watch -f
-            else
-              echo "index.js not found!"
-              exit 1
-            fi
-          EOF
-      - name: Configure Nginx
-        env:
-          SSH_PRIVATE_KEY_1: ${{ secrets.SSH_PRIVATE_KEY }}
-          SSH_USERNAME_1: ${{ secrets.USERNAME }}
-          SSH_HOST_1: ${{ secrets.HOST }}
-        run: >
-          echo "$SSH_PRIVATE_KEY_1" > private_key.pem
+      #     ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF
+      #       cd /home/$SSH_USERNAME_1/backend-$DEPLOY_ENV
+      #       sudo apt update
+      #       sudo apt install npm -y
+      #       sudo npm install -g pm2 -y
+      #       if [ -f package.json ]; then
+      #         npm install
+      #       else
+      #         echo "package.json not found!"
+      #         exit 1
+      #       fi
+      #       if [ -f index.js ]; then
+      #         pm2 stop backend-$DEPLOY_ENV || true
+      #         pm2 start index.js --name backend-$DEPLOY_ENV --watch -f
+      #       else
+      #         echo "index.js not found!"
+      #         exit 1
+      #       fi
+      #     EOF
+      # - name: Configure Nginx
+      #   env:
+      #     SSH_PRIVATE_KEY_1: ${{ secrets.SSH_PRIVATE_KEY }}
+      #     SSH_USERNAME_1: ${{ secrets.USERNAME }}
+      #     SSH_HOST_1: ${{ secrets.HOST }}
+      #   run: >
+      #     echo "$SSH_PRIVATE_KEY_1" > private_key.pem
 
-          chmod 600 private_key.pem
-
-
-          ACTIVE_ENV=$(ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 'if [ -d /home/$SSH_USERNAME_1/backend-blue ]; then echo "blue"; else echo "green"; fi')
-
-          echo "ACTIVE_ENV=$ACTIVE_ENV" >> $GITHUB_ENV
-
-          echo "Active environment: $ACTIVE_ENV"
+      #     chmod 600 private_key.pem
 
 
-          if [ "$ACTIVE_ENV" == "blue" ]; then
+      #     ACTIVE_ENV=$(ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 'if [ -d /home/$SSH_USERNAME_1/backend-blue ]; then echo "blue"; else echo "green"; fi')
+
+      #     echo "ACTIVE_ENV=$ACTIVE_ENV" >> $GITHUB_ENV
+
+      #     echo "Active environment: $ACTIVE_ENV"
+
+
+      #     if [ "$ACTIVE_ENV" == "blue" ]; then
           
-            NEW_ENV="green"
+      #       NEW_ENV="green"
             
-          else
+      #     else
           
-            NEW_ENV="blue"
+      #       NEW_ENV="blue"
 
-          fi
+      #     fi
 
-          echo "Switching to: $NEW_ENV"
+      #     echo "Switching to: $NEW_ENV"
 
-          scp -i private_key.pem default.template $SSH_USERNAME_1@$SSH_HOST_1:/tmp/default.template
-          ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF      
-          export ACTIVE_ENV=$NEW_ENV
+      #     scp -i private_key.pem default.template $SSH_USERNAME_1@$SSH_HOST_1:/tmp/default.template
+      #     ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF      
+      #     export ACTIVE_ENV=$NEW_ENV
 
-          #envsubst '\$ACTIVE_ENV' < /tmp/default.template > /etc/nginx/sites-available/default
+      #     #envsubst '\$ACTIVE_ENV' < /tmp/default.template > /etc/nginx/sites-available/default
             
-            # envsubst '\$ACTIVE_ENV'  /tmp/default.template > /etc/nginx/sites-available/default
-            sed -i 's/\$ACTIVE_ENV/$NEW_ENV/g' /tmp/default.template
-            sudo cp /tmp/default.template /etc/nginx/sites-available/default
+      #       # envsubst '\$ACTIVE_ENV'  /tmp/default.template > /etc/nginx/sites-available/default
+      #       sed -i 's/\$ACTIVE_ENV/$NEW_ENV/g' /tmp/default.template
+      #       sudo cp /tmp/default.template /etc/nginx/sites-available/default
 
-            sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
-            sudo nginx -t
-            sudo systemctl start nginx
-            sudo systemctl reload nginx
-          EOF
-      - name: Test Deployment
-        env:
-          SSH_HOST_1: ${{ secrets.HOST }}
-        run: >
-          curl -s http://localhost/sayHello || (echo "Deployment failed!" && exit
-          1)
+      #       sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
+      #       sudo nginx -t
+      #       sudo systemctl start nginx
+      #       sudo systemctl reload nginx
+      #     EOF
+      # - name: Test Deployment
+      #   env:
+      #     SSH_HOST_1: ${{ secrets.HOST }}
+      #   run: >
+      #     curl -s http://localhost/sayHello || (echo "Deployment failed!" && exit
+      #     1)
