Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -49,7 +49,12 @@ jobs:
             sudo apt install npm -y
             sudo npm install -g pm2
             # Ensure the package.json file is present
-            npm install
+            if [ -f /home/$USERNAME/backend-blue/package.json ]; then
+              npm install
+            else
+              echo "package.json not found!"
+              exit 1
+            fi
             
 
             # Check if index.js exists
