Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,18 +34,16 @@ jobs:
           ACTIVE_ENV=$(ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 'if [ -d /home/$SSH_USERNAME_1/backend-green ]; then echo "blue"; else echo "green"; fi')
 
           echo "ACTIVE_ENV=$ACTIVE_ENV" >> $GITHUB_ENV
-          
+
           echo "Active environment: $ACTIVE_ENV"
 
-
-          # Determine non-active environment
 
           if [ "$ACTIVE_ENV" == "blue" ]; then
             DEPLOY_ENV="green"
           else
             DEPLOY_ENV="blue"
           fi
-          
+
           echo "Deploying to: $DEPLOY_ENV"
 
 
@@ -68,7 +66,6 @@ jobs:
             if [ -f index.js ]; then
               pm2 stop backend-$DEPLOY_ENV || true
               pm2 start index.js --name backend-$DEPLOY_ENV --watch -f
-              # pm2 restart index.js --name backend-$DEPLOY_ENV --watch -f
             else
               echo "index.js not found!"
               exit 1
@@ -87,43 +84,33 @@ jobs:
 
           ACTIVE_ENV=$(ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 'if [ -d /home/$SSH_USERNAME_1/backend-green ]; then echo "blue"; else echo "green"; fi')
 
-          
           echo "ACTIVE_ENV=$ACTIVE_ENV" >> $GITHUB_ENV
-          
-          
+
           echo "Active environment: $ACTIVE_ENV"
 
-
-          # Determine non-active environment 
 
           if [ "$ACTIVE_ENV" == "blue" ]; then
             NEW_ENV="green"
           else
             NEW_ENV="blue"
           fi
-          
-          
+
           echo "Switching to: $NEW_ENV"
 
 
-          # Upload Nginx configuration 
+          scp -i private_key.pem /etc/nginx/sites-available/default.template $SSH_USERNAME_1@$SSH_HOST_1:/tmp/default.template
 
-          scp -i private_key.pem nginx.conf $SSH_USERNAME_1@$SSH_HOST_1:/tmp/nginx.conf
-
-
-          # Apply Nginx configuration 
 
           ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF
             export ACTIVE_ENV=$NEW_ENV
-            envsubst '${ACTIVE_ENV}' < /tmp/nginx.conf > /etc/nginx/sites-available/default
-            # sudo sed -i "s|backend-\(blue\|green\)|backend-$NEW_ENV|g" /tmp/nginx.conf
-            # sudo mv /tmp/nginx.conf /etc/nginx/sites-available/default
+            envsubst '${ACTIVE_ENV}' < /tmp/default.template > /etc/nginx/sites-available/default
             sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
             sudo nginx -t
             sudo systemctl reload nginx
           EOF
       - name: Test Deployment
         env:
-          SSH_HOST_1: ${{ secrets.SSH_HOST_1 }}
-        run: |
-          curl -s http://localhost/sayHello || (echo "Deployment failed!" && exit 1)
+          SSH_HOST_1: ${{ secrets.HOST }}
+        run: >
+          curl -s http://$SSH_HOST_1/sayHello || (echo "Deployment failed!" && exit
+          1)
