Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -40,8 +40,6 @@ jobs:
           echo "Active environment: $ACTIVE_ENV"
 
 
-          # Determine deployment directory
-
           if [ "$ACTIVE_ENV" = "blue" ]; then
             DEPLOY_DIR="/home/$SSH_USERNAME_1/backend-green"
           else
@@ -61,7 +59,6 @@ jobs:
 
           scp -i private_key.pem -r ./* $SSH_USERNAME_1@$SSH_HOST_1:$DEPLOY_DIR/
 
-
           # Execute deployment steps
 
           ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF
@@ -69,39 +66,25 @@ jobs:
             echo 'Deployment steps go here'
           EOF
 
-          # if [ "$ACTIVE_ENV" == "blue" ]; then
-          #   DEPLOY_ENV="green"
-          # else
-          #   DEPLOY_ENV="blue"
-          # fi
-
-          # echo "Deploying to: $DEPLOY_ENV"
-
-
-          # ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 "mkdir -p /home/$SSH_USERNAME_1/backend-$DEPLOY_ENV"
-
-          # scp -i private_key.pem -r ./* $SSH_USERNAME_1@$SSH_HOST_1:/home/$SSH_USERNAME_1/backend-$DEPLOY_ENV/
-
-
-      #     ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF
-      #       cd /home/$SSH_USERNAME_1/backend-$DEPLOY_ENV
-      #       sudo apt update
-      #       sudo apt install npm -y
-      #       sudo npm install -g pm2 -y
-      #       if [ -f package.json ]; then
-      #         npm install
-      #       else
-      #         echo "package.json not found!"
-      #         exit 1
-      #       fi
-      #       if [ -f index.js ]; then
-      #         pm2 stop backend-$DEPLOY_ENV || true
-      #         pm2 start index.js --name backend-$DEPLOY_ENV --watch -f
-      #       else
-      #         echo "index.js not found!"
-      #         exit 1
-      #       fi
-      #     EOF
+          ssh -i private_key.pem $SSH_USERNAME_1@$SSH_HOST_1 << EOF
+            cd /home/$SSH_USERNAME_1/$DEPLOY_DIR
+            sudo apt update
+            sudo apt install npm -y
+            sudo npm install -g pm2 -y
+            if [ -f package.json ]; then
+              npm install
+            else
+              echo "package.json not found!"
+              exit 1
+            fi
+            if [ -f index.js ]; then
+              pm2 stop backend-$DEPLOY_DIR || true
+              pm2 start index.js --name backend-$DEPLOY_DIR --watch -f
+            else
+              echo "index.js not found!"
+              exit 1
+            fi
+          EOF
       # - name: Configure Nginx
       #   env:
       #     SSH_PRIVATE_KEY_1: ${{ secrets.SSH_PRIVATE_KEY }}
